name: shelfpeople
description: a people api
version: 0.0.2
publish_to: none
# author: alexmerced

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  postgres: ^2.4.1+2

dev_dependencies:
  build_runner: ^2.1.4
  build_test: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.1