name: shelfpeople
description: a people api
version: 0.0.1
author: alexmerced

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  postgres: ^2.2.0

dev_dependencies:
  build_runner: ^1.11.0
  build_test: ^1.3.0
  build_web_compilers: ^2.12.0